--- 
install: 
  - "npm ci"
language: node_js
node_js: 
  - node
notification: 
  email: false
script: 
  - "npm test"
after_success: 
  npm run coverage
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE free_mentors;' -U postgres